{
 "title": "Grafana metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "annotation.io.kubernetes.container.ports",
       "operator": "=",
       "value": "[{\"containerPort\":3000,\"protocol\":\"TCP\"}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Mem usage_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      {
       "key": "annotation.io.kubernetes.container.ports",
       "operator": "=",
       "value": "[{\"containerPort\":3000,\"protocol\":\"TCP\"}]"
      }
     ]
    }
   ]
  },
  {
   "title": "io_serviced_recursive_sync",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       { "params": [ "io_serviced_recursive_sync" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      {
       "key": "annotation.io.kubernetes.container.ports",
       "operator": "=",
       "value": "[{\"containerPort\":3000,\"protocol\":\"TCP\"}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Network rx_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      {
       "key": "annotation.io.kubernetes.container.ports",
       "operator": "=",
       "value": "[{\"containerPort\":3000,\"protocol\":\"TCP\"}]"
      }
     ]
    }
   ]
  }
 ]
}