apiVersion: apps/v1
kind: Deployment
metadata:
    name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-alpine
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 21000
          hostPort: 21000
        - containerPort: 21001
          hostPort: 21001
        - containerPort: 21002
          hostPort: 21002
        - containerPort: 21003
          hostPort: 21003
        - containerPort: 21004
          hostPort: 21004
        - containerPort: 21005
          hostPort: 21005
        - containerPort: 21006
          hostPort: 21006
        - containerPort: 21007
          hostPort: 21007
        - containerPort: 21008
          hostPort: 21008
        - containerPort: 21009
          hostPort: 21009
        - containerPort: 21010
          hostPort: 21010
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
    - name: http0
      port: 21000
    - name: http1
      port: 21001
    - name: http2
      port: 21002
    - name: http3
      port: 21003
    - name: http4
      port: 21004
    - name: http5
      port: 21005
    - name: http6
      port: 21006
    - name: http7
      port: 21007
    - name: http8
      port: 21008
    - name: http9
      port: 21009
    - name: http10
      port: 21010
  type: LoadBalancer
